name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: compile
      run: g++ main.cpp -o whatsnext
      
    - name: check executable
      run: bash -c "[[ -x whatsnext ]]"
