name: build for linux

on:
  push:
    branches: ['main']
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: compile
      run: g++ main.cpp -o whatsnext

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: whatsnext-linux
        path: whatsnext
        
