name: build for windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: check installation
      run: |
        gcc --version 
        g++ --version 
        gdb --version
    - name: compile
      run: g++ main.cpp -o whatsnext.exe

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: whatsnext-windows
        path: whatsnext.exe
        
